spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost/cms?serverTimezone=UTC
    username: root
    password: iss2020
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /cms/api/

logging:
  level:
    com:
      cms:
        interceptor:
          DEBUG
    root: INFO

predefined:
  admin:
    username: admin

